name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [publish-event]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.action == 'publish-event'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_OCEAN_0BD8A5303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTACTEMAIL: ${{ secrets.CONTACTEMAIL }}
          CONTACTNAME: ${{ secrets.CONTACTNAME }}